# Ignore Table Column Config.
ignores:
  - table: sys_tables
#  - table: base_skill_level
#    columns:
#      - skill_id
#  - table: base_buff
#    columns:
#      - conflict_tags
#      - conflict_self
